parameters:
#    cts_recipes.example.class: Cts\RecipesBundle\Example
    cts_recipes.recipes_collection.class: Cts\RecipesBundle\Services\CollectionRecipe
    cts_recipes.recipes_collection.file_path: ../src/Cts/RecipesBundle/Services/fixtures/recipes.json
#    cts_recipes.recipes_collection.recipe1.time: 24
#    cts_recipes.recipes_collection.recipe1.ing: "200g Jautienos 150g Surio 1 Supjaustytas Batonas 1 Skardine Alaus Prieskoniai Ranka ant Peties"
#    cts_recipes.recipes_collection.recipe1.about: "Mėsos gabalą virti garų puode apie valandą laiko (prieš virimą mėsą 1 val. pamarinuoti garstyčiose). Tada sudėti supjaustytas morkas, porą, salierą ir petražoles ir troškinti 40 minučių.Ant mėsos berti pipirų, druskos, sudėti lauro lapus."

services:
    cts_recipes.recipes_collection:
        class: %cts_recipes.recipes_collection.class%
        calls:
            - [setRootDir, [%kernel.root_dir%]]
            - [setFixtureFile, [%cts_recipes.recipes_collection.file_path%]]
#        	- [setRecipeTime [%cts_recipes.recipes_collection.recipe1.time%]]
#        	- [setRecipeIngridient [%cts_recipes.recipes_collection.recipe1.ing%]]
#        	- [setRecipeAbout [%cts_recipes.recipes_collection.recipe1.about%]]
